name: Gladshoppy Online
favicon: null
layout_spectrum: 0.48541
typography_spectrum: 0.0025693729985505342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5
  lightness: 0.07105289469473064
  saturation: 0.010370185831561685
  rhythmicContrast: 0.8232957397121936
purpose: []
